#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H


#define CONFIG_GRAVITY_AY 3
#define CONFIG_MAX_GRAVITY_VY 13

#define CONFIG_WEATHER_TIME_MIN 10 // In seconds
#define CONFIG_WEATHER_TIME_MAX 30 // In seconds
#define CONFIG_WEATHER_STRENGTH_MIN 0.5
#define CONFIG_WEATHER_STRENGTH_MAX 1.5


#endif